# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Weather(object):
    def setupUi(self, Weather):
        Weather.setObjectName("Weather")
        Weather.resize(310, 250)
        Weather.setMinimumSize(QtCore.QSize(234, 250))
        Weather.setMaximumSize(QtCore.QSize(386, 250))
        self.centralwidget = QtWidgets.QWidget(Weather)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cur_img = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cur_img.sizePolicy().hasHeightForWidth())
        self.cur_img.setSizePolicy(sizePolicy)
        self.cur_img.setMaximumSize(QtCore.QSize(50, 50))
        self.cur_img.setText("")
        self.cur_img.setPixmap(QtGui.QPixmap("imgs/01d.png"))
        self.cur_img.setIndent(0)
        self.cur_img.setObjectName("cur_img")
        self.horizontalLayout.addWidget(self.cur_img)
        self.cur_city = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(14)
        self.cur_city.setFont(font)
        self.cur_city.setIndent(0)
        self.cur_city.setObjectName("cur_city")
        self.horizontalLayout.addWidget(self.cur_city)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cur_description = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(10)
        self.cur_description.setFont(font)
        self.cur_description.setObjectName("cur_description")
        self.horizontalLayout.addWidget(self.cur_description)
        self.cur_temp = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(10)
        self.cur_temp.setFont(font)
        self.cur_temp.setObjectName("cur_temp")
        self.horizontalLayout.addWidget(self.cur_temp)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 310, 196))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(6, 0, 6, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setMinimumSize(QtCore.QSize(70, 181))
        self.widget.setMaximumSize(QtCore.QSize(70, 181))
        self.widget.setStyleSheet("background-color:#F4f4f4; border-radius:8px;")
        self.widget.setObjectName("widget")
        self.date_1 = QtWidgets.QLabel(self.widget)
        self.date_1.setGeometry(QtCore.QRect(0, 11, 70, 24))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(9)
        self.date_1.setFont(font)
        self.date_1.setWordWrap(True)
        self.date_1.setObjectName("date_1")
        self.img_1 = QtWidgets.QLabel(self.widget)
        self.img_1.setGeometry(QtCore.QRect(10, 32, 50, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_1.sizePolicy().hasHeightForWidth())
        self.img_1.setSizePolicy(sizePolicy)
        self.img_1.setMaximumSize(QtCore.QSize(50, 50))
        self.img_1.setText("")
        self.img_1.setPixmap(QtGui.QPixmap("imgs/01d.png"))
        self.img_1.setIndent(0)
        self.img_1.setObjectName("img_1")
        self.desc_1 = QtWidgets.QLabel(self.widget)
        self.desc_1.setGeometry(QtCore.QRect(0, 78, 70, 101))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(9)
        self.desc_1.setFont(font)
        self.desc_1.setWordWrap(True)
        self.desc_1.setObjectName("desc_1")
        self.horizontalLayout_2.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_2.setMinimumSize(QtCore.QSize(70, 181))
        self.widget_2.setMaximumSize(QtCore.QSize(70, 181))
        self.widget_2.setStyleSheet("background-color:#F4f4f4; border-radius:8px;")
        self.widget_2.setObjectName("widget_2")
        self.date_2 = QtWidgets.QLabel(self.widget_2)
        self.date_2.setGeometry(QtCore.QRect(0, 11, 70, 24))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(9)
        self.date_2.setFont(font)
        self.date_2.setWordWrap(True)
        self.date_2.setObjectName("date_2")
        self.img_2 = QtWidgets.QLabel(self.widget_2)
        self.img_2.setGeometry(QtCore.QRect(10, 32, 50, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_2.sizePolicy().hasHeightForWidth())
        self.img_2.setSizePolicy(sizePolicy)
        self.img_2.setMaximumSize(QtCore.QSize(50, 50))
        self.img_2.setText("")
        self.img_2.setPixmap(QtGui.QPixmap("imgs/01d.png"))
        self.img_2.setIndent(0)
        self.img_2.setObjectName("img_2")
        self.desc_2 = QtWidgets.QLabel(self.widget_2)
        self.desc_2.setGeometry(QtCore.QRect(0, 78, 70, 101))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(9)
        self.desc_2.setFont(font)
        self.desc_2.setWordWrap(True)
        self.desc_2.setObjectName("desc_2")
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_3.setMinimumSize(QtCore.QSize(70, 181))
        self.widget_3.setMaximumSize(QtCore.QSize(70, 181))
        self.widget_3.setStyleSheet("background-color:#F4f4f4; border-radius:8px;")
        self.widget_3.setObjectName("widget_3")
        self.date_3 = QtWidgets.QLabel(self.widget_3)
        self.date_3.setGeometry(QtCore.QRect(0, 11, 70, 24))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(9)
        self.date_3.setFont(font)
        self.date_3.setWordWrap(True)
        self.date_3.setObjectName("date_3")
        self.img_3 = QtWidgets.QLabel(self.widget_3)
        self.img_3.setGeometry(QtCore.QRect(10, 32, 50, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_3.sizePolicy().hasHeightForWidth())
        self.img_3.setSizePolicy(sizePolicy)
        self.img_3.setMaximumSize(QtCore.QSize(50, 50))
        self.img_3.setText("")
        self.img_3.setPixmap(QtGui.QPixmap("imgs/01d.png"))
        self.img_3.setIndent(0)
        self.img_3.setObjectName("img_3")
        self.desc_3 = QtWidgets.QLabel(self.widget_3)
        self.desc_3.setGeometry(QtCore.QRect(0, 78, 70, 101))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(9)
        self.desc_3.setFont(font)
        self.desc_3.setWordWrap(True)
        self.desc_3.setObjectName("desc_3")
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_4.setMinimumSize(QtCore.QSize(70, 181))
        self.widget_4.setMaximumSize(QtCore.QSize(70, 181))
        self.widget_4.setStyleSheet("background-color:#F4f4f4; border-radius:8px;")
        self.widget_4.setObjectName("widget_4")
        self.date_4 = QtWidgets.QLabel(self.widget_4)
        self.date_4.setGeometry(QtCore.QRect(0, 11, 70, 24))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(9)
        self.date_4.setFont(font)
        self.date_4.setWordWrap(True)
        self.date_4.setObjectName("date_4")
        self.img_4 = QtWidgets.QLabel(self.widget_4)
        self.img_4.setGeometry(QtCore.QRect(10, 32, 50, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_4.sizePolicy().hasHeightForWidth())
        self.img_4.setSizePolicy(sizePolicy)
        self.img_4.setMaximumSize(QtCore.QSize(50, 50))
        self.img_4.setText("")
        self.img_4.setPixmap(QtGui.QPixmap("imgs/01d.png"))
        self.img_4.setIndent(0)
        self.img_4.setObjectName("img_4")
        self.desc_4 = QtWidgets.QLabel(self.widget_4)
        self.desc_4.setGeometry(QtCore.QRect(0, 78, 70, 101))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(9)
        self.desc_4.setFont(font)
        self.desc_4.setWordWrap(True)
        self.desc_4.setObjectName("desc_4")
        self.horizontalLayout_2.addWidget(self.widget_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        Weather.setCentralWidget(self.centralwidget)

        self.retranslateUi(Weather)
        QtCore.QMetaObject.connectSlotsByName(Weather)

    def retranslateUi(self, Weather):
        _translate = QtCore.QCoreApplication.translate
        Weather.setWindowTitle(_translate("Weather", "MainWindow"))
        self.cur_city.setText(_translate("Weather", "London"))
        self.cur_description.setText(_translate("Weather", "clear sky"))
        self.cur_temp.setText(_translate("Weather", "25°"))
        self.date_1.setText(_translate("Weather", "<html><head/><body><center><p>2019-06-10 09:00</p></center></body></html>"))
        self.desc_1.setText(_translate("Weather", "<html><head/><body><p align=\"center\">25°/30°</p><p align=\"center\"><span style=\" font-family:\'Lucida Grande\'; color:#000000;\">Humidity<br/>87% </span></p><p align=\"center\"><span style=\" font-family:\'Lucida Grande\'; color:#000000;\">Cloudiness<br>88%</span></p></body></html>"))
        self.date_2.setText(_translate("Weather", "<html><head/><body><center><p>2019-06-10 09:00</p></center></body></html>"))
        self.desc_2.setText(_translate("Weather", "<html><head/><body><p align=\"center\">25°/30°</p><p align=\"center\"><span style=\" font-family:\'Lucida Grande\'; color:#000000;\">Humidity<br/>87% </span></p><p align=\"center\"><span style=\" font-family:\'Lucida Grande\'; color:#000000;\">Cloudiness<br>88%</span></p></body></html>"))
        self.date_3.setText(_translate("Weather", "<html><head/><body><center><p>2019-06-10 09:00</p></center></body></html>"))
        self.desc_3.setText(_translate("Weather", "<html><head/><body><p align=\"center\">25°/30°</p><p align=\"center\"><span style=\" font-family:\'Lucida Grande\'; color:#000000;\">Humidity<br/>87% </span></p><p align=\"center\"><span style=\" font-family:\'Lucida Grande\'; color:#000000;\">Cloudiness<br>88%</span></p></body></html>"))
        self.date_4.setText(_translate("Weather", "<html><head/><body><center><p>2019-06-10 09:00</p></center></body></html>"))
        self.desc_4.setText(_translate("Weather", "<html><head/><body><p align=\"center\">25°/30°</p><p align=\"center\"><span style=\" font-family:\'Lucida Grande\'; color:#000000;\">Humidity<br/>87% </span></p><p align=\"center\"><span style=\" font-family:\'Lucida Grande\'; color:#000000;\">Cloudiness<br>88%</span></p></body></html>"))

