# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Weather(object):
    def setupUi(self, Weather):
        Weather.setObjectName("Weather")
        Weather.resize(310, 250)
        Weather.setMinimumSize(QtCore.QSize(234, 250))
        Weather.setMaximumSize(QtCore.QSize(386, 250))
        self.centralwidget = QtWidgets.QWidget(Weather)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
            "background-color:#FFF;\n"
            "}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_5 = QtWidgets.QWidget(self.centralwidget)
        self.widget_5.setStyleSheet("#widget_5{\n"
"background-color:#F4F4F4;\n"
"border:none;\n"
"}")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cur_img = QtWidgets.QLabel(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cur_img.sizePolicy().hasHeightForWidth())
        self.cur_img.setSizePolicy(sizePolicy)
        self.cur_img.setMaximumSize(QtCore.QSize(50, 50))
        self.cur_img.setText("")
        self.cur_img.setPixmap(QtGui.QPixmap("imgs/01d.png"))
        self.cur_img.setIndent(0)
        self.cur_img.setObjectName("cur_img")
        self.horizontalLayout.addWidget(self.cur_img)
        self.cur_city = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(16)
        self.cur_city.setFont(font)
        self.cur_city.setIndent(0)
        self.cur_city.setObjectName("cur_city")
        self.horizontalLayout.addWidget(self.cur_city)
        spacerItem = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cur_description = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(12)
        self.cur_description.setFont(font)
        self.cur_description.setObjectName("cur_description")
        self.horizontalLayout.addWidget(self.cur_description)
        self.cur_temp = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(12)
        self.cur_temp.setFont(font)
        self.cur_temp.setObjectName("cur_temp")
        self.horizontalLayout.addWidget(self.cur_temp)
        self.verticalLayout.addWidget(self.widget_5)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("border:none;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 310, 200))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setStyleSheet("#scrollAreaWidgetContents{\n"
            "background-color:#FFF;\n"
            "}")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(6, 0, 6, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        """
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setMinimumSize(QtCore.QSize(70, 181))
        self.widget.setMaximumSize(QtCore.QSize(70, 181))
        self.widget.setStyleSheet("background-color:#F4f4f4; border-radius:8px;")
        self.widget.setObjectName("widget")
        self.date = QtWidgets.QLabel(self.widget)
        self.date.setGeometry(QtCore.QRect(0, 10, 70, 36))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(10)
        self.date.setFont(font)
        self.date.setAlignment(QtCore.Qt.AlignTop)
        self.date.setWordWrap(True)
        #self.date.setObjectName("date")
        self.img = QtWidgets.QLabel(self.widget)
        self.img.setGeometry(QtCore.QRect(10, 32, 50, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img.sizePolicy().hasHeightForWidth())
        self.img.setSizePolicy(sizePolicy)
        self.img.setMaximumSize(QtCore.QSize(50, 50))
        self.img.setText("")
        self.img.setPixmap(QtGui.QPixmap("imgs/01d.png"))
        self.img.setIndent(0)
        #self.img.setObjectName("img")
        self.desc = QtWidgets.QLabel(self.widget)
        self.desc.setGeometry(QtCore.QRect(0, 78, 70, 101))
        font = QtGui.QFont()
        font.setFamily("Lucida Grande")
        font.setPointSize(11)
        self.desc.setFont(font)
        self.desc.setWordWrap(True)
        #self.desc.setObjectName("desc")
        self.horizontalLayout_2.addWidget(self.widget)
        """
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        Weather.setCentralWidget(self.centralwidget)

        self.retranslateUi(Weather)
        QtCore.QMetaObject.connectSlotsByName(Weather)

    def retranslateUi(self, Weather):
        _translate = QtCore.QCoreApplication.translate
        Weather.setWindowTitle(_translate("Weather", "Weather Forecast"))
        self.cur_city.setText(_translate("Weather", "London"))
        self.cur_description.setText(_translate("Weather", "clear sky"))
        self.cur_temp.setText(_translate("Weather", "25°"))
        #self.date_1.setText(_translate("Weather", "<html><head/><body><center><p>2019-06-10 09:00</p></center></body></html>"))
        #self.desc_1.setText(_translate("Weather", "<html><head/><body><p align=\"center\">25°/30°</p><p align=\"center\"><span style=\" font-family:\'Lucida Grande\'; color:#000000;\">Humidity<br/>87% </span></p><p align=\"center\"><span style=\" font-family:\'Lucida Grande\'; color:#000000;\">Cloudiness<br>88%</span></p></body></html>"))

